rm hackable_engine/board/chess/*cpython*
rm hackable_engine/board/hex/*cpython*
rm hackable_engine/common/queue/items/*cpython*
rm hackable_engine/criteria/evaluation/*.cpython*
rm hackable_engine/criteria/evaluation/chess/*.cpython*
rm hackable_engine/criteria/evaluation/hex/*.cpython*
rm hackable_engine/criteria/selection/*.cpython*
rm hackable_engine/game_tree/*.cpython*
rm hackable_engine/training/envs/*.cpython*

mypyc hackable_engine/board/chess/chess_board.py
mypyc hackable_engine/board/hex/hex_board.py
mypyc hackable_engine/common/queue/items/base_item.py
mypyc hackable_engine/common/queue/items/control_item.py
mypyc hackable_engine/common/queue/items/distributor_item.py
mypyc hackable_engine/common/queue/items/eval_item.py
mypyc hackable_engine/common/queue/items/selector_item.py
mypyc hackable_engine/criteria/selection/fast_selector.py
mypyc hackable_engine/criteria/evaluation/base_eval.py
mypyc hackable_engine/criteria/evaluation/chess/square_control_eval.py
mypyc hackable_engine/criteria/evaluation/hex/simple_eval.py
mypyc hackable_engine/game_tree/node.py
mypyc hackable_engine/game_tree/traverser.py
mypyc hackable_engine/training/envs/chess/square_control_env_util.py
mypyc hackable_engine/training/envs/chess/square_control_env_single_action_util.py
