from cffi import FFI

ffibuilder = FFI()

# Specify the header that was generated by the Go compiler for source
# Specify the shared object that was generated by the Go compiler for extra_objects
ffibuilder.set_source(
    module_name="go_board",
    source="""
        #include "go_board.h"
    """,
    extra_objects=["go_board.so"],
)

# Copy the extern functions at the bottom of the header file (e.g. hello.h)
# ffibuilder.cdef(
#     csource="""
#     extern int get_mobility(char* p0, char* p1);
#     """
# )
ffibuilder.cdef(
    csource="""
    extern char* get_board_data(char* p0, char* p1);

    extern char* get_moves(char* p0);
    
    extern int get_mobility(char* p0, char* p1);
    
    extern char* get_fen(char* p0, char* p1);
    
    extern void pyfree(char* p0);
    """
)

if __name__ == "__main__":
    ffibuilder.compile(verbose=True)
